services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: customer_database
      POSTGRES_USER: customer_admin
      POSTGRES_PASSWORD: admin_password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5333:5432"
    networks:
      - postgres
    restart: unless-stopped

  customer-api:
    container_name: customer-api
    image: vincevanderberg/customer-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer_database
    ports:
      - "8080:1234"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
